CREATE DATABASE IF NOT EXISTS productdb;
USE productdb;
CREATE TABLE products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  idate DATE NOT NULL,
  quantity INT NOT NULL
);
